// SPDX-License-Identifier: GPL-3.0-or-later

import AjarCore
import Metal

/// Typed failures while producing the FR-MED-007 placeholder frame.
public enum OfflineSlateRenderError: Error, Equatable, Sendable {
    /// Width and height must be positive and safely allocatable.
    case invalidDimensions(PixelDimensions)

    /// Metal could not allocate the source texture.
    case textureCreationFailed(PixelDimensions)

    /// Generated bytes unexpectedly had no storage.
    case pixelStorageUnavailable
}

/// Deterministic, text-free offline placeholder frame.
public enum OfflineSlateRenderer {
    /// Keeps malformed persisted metadata from requesting an allocation large enough to
    /// terminate the process. The limit admits an 8K UHD frame (127 MiB of BGRA8 pixels).
    private static let maximumPixelByteCount = 128 * 1_024 * 1_024
    private static let backgroundBGRA: [UInt8] = [44, 24, 92, 255]
    private static let stripeBGRA: [UInt8] = [76, 42, 156, 255]
    private static let stripePeriod = 24
    private static let stripeWidth = 6

    /// Generates tight-packed BGRA8 bytes: a solid plum field with diagonal warning bands.
    public static func bgra8Pixels(
        dimensions: PixelDimensions
    ) throws -> [UInt8] {
        guard dimensions.width > 0, dimensions.height > 0 else {
            throw OfflineSlateRenderError.invalidDimensions(dimensions)
        }
        let (pixelCount, pixelOverflow) = dimensions.width.multipliedReportingOverflow(
            by: dimensions.height
        )
        let (byteCount, byteOverflow) = pixelCount.multipliedReportingOverflow(by: 4)
        guard
            !pixelOverflow,
            !byteOverflow,
            byteCount <= maximumPixelByteCount
        else {
            throw OfflineSlateRenderError.invalidDimensions(dimensions)
        }

        var pixels = [UInt8](repeating: 0, count: byteCount)
        for yPosition in 0..<dimensions.height {
            for xPosition in 0..<dimensions.width {
                let diagonalPosition = (xPosition + yPosition) % stripePeriod
                let color = diagonalPosition < stripeWidth ? stripeBGRA : backgroundBGRA
                let offset = (yPosition * dimensions.width + xPosition) * 4
                pixels[offset] = color[0]
                pixels[offset + 1] = color[1]
                pixels[offset + 2] = color[2]
                pixels[offset + 3] = color[3]
            }
        }
        return pixels
    }

    /// Uploads the deterministic placeholder to a shared BGRA8 Metal texture.
    public static func makeTexture(
        device: MTLDevice,
        dimensions: PixelDimensions
    ) throws -> MTLTexture {
        let pixels = try bgra8Pixels(dimensions: dimensions)
        let descriptor = MTLTextureDescriptor.texture2DDescriptor(
            pixelFormat: .bgra8Unorm,
            width: dimensions.width,
            height: dimensions.height,
            mipmapped: false
        )
        descriptor.storageMode = .shared
        descriptor.usage = [.shaderRead]
        guard let texture = device.makeTexture(descriptor: descriptor) else {
            throw OfflineSlateRenderError.textureCreationFailed(dimensions)
        }

        var replaced = false
        pixels.withUnsafeBytes { rawBuffer in
            guard let baseAddress = rawBuffer.baseAddress else {
                return
            }
            texture.replace(
                region: MTLRegionMake2D(0, 0, dimensions.width, dimensions.height),
                mipmapLevel: 0,
                withBytes: baseAddress,
                bytesPerRow: dimensions.width * 4
            )
            replaced = true
        }
        guard replaced else {
            throw OfflineSlateRenderError.pixelStorageUnavailable
        }
        return texture
    }
}
